# Generated by Django 4.0.6 on 2024-04-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Cientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('objetivos', models.TextField()),
                ('competencias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curricular_unit_readable_code', models.CharField(max_length=20)),
                ('area_cientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIG.area_cientifica')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIG.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Linguagem_Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('conceitos_aplicados', models.TextField()),
                ('tecnologias_utilizadas', models.TextField()),
                ('imagem', models.ImageField(upload_to='projeto_images/')),
                ('video_youtube', models.URLField()),
                ('repositorio_github', models.URLField(blank=True, null=True)),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LIG.disciplina')),
                ('linguagens_programacao', models.ManyToManyField(to='LIG.linguagem_programacao')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(to='LIG.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='docentes',
            field=models.ManyToManyField(to='LIG.docente'),
        ),
    ]
