# Generated by Django 4.0.6 on 2024-06-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIG', '0002_alter_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='projeto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LIG.projeto'),
        ),
    ]
