# Generated by Django 4.0.6 on 2024-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIG', '0003_remove_projeto_disciplina_disciplina_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='video_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
