# Generated by Django 4.0.6 on 2024-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIG', '0004_alter_projeto_video_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='conceitos_aplicados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projeto_images/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagens_programacao',
            field=models.ManyToManyField(blank=True, to='LIG.linguagem_programacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias_utilizadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
