# Generated by Django 4.0.6 on 2024-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIG', '0005_alter_projeto_conceitos_aplicados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
