# Generated by Django 4.0.6 on 2024-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIG', '0007_alter_disciplina_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='disciplinas',
        ),
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
