# Generated by Django 4.0.6 on 2024-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_alter_albuns_banda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuns',
            name='capa',
            field=models.ImageField(blank=True, upload_to='album_fotos/'),
        ),
    ]
