# Generated by Django 4.0.6 on 2024-06-03 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_albuns_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaFundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_fundo', models.ImageField(upload_to='cena_fundo/')),
            ],
        ),
        migrations.AlterField(
            model_name='albuns',
            name='ano_lancamento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='bandas',
            name='ano_criacao',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='duracao',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='link',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
