# Generated by Django 4.0.6 on 2024-06-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_capafundo_alter_albuns_ano_lancamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuns',
            name='capa',
            field=models.ImageField(blank=True, upload_to='capa_fotos/'),
        ),
    ]
