# Generated by Django 4.0.6 on 2024-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_alter_albuns_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capafundo',
            name='foto_fundo',
        ),
        migrations.AddField(
            model_name='capafundo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='capas_fundo/'),
        ),
        migrations.AddField(
            model_name='capafundo',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
